[package]
name = "mips-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicorn-engine = "2.0.0-rc7"
#unicorn = "0.9.1"
#unicorn-rs = "0.1.0"
